"""
Let the AI WRITE a semantic model automatically from a profile of the real data.

  python generate_semantic.py --provider groq       # FREE key -> semantic/olist_auto.yaml
  python generate_semantic.py --provider profile    # no AI: save only the profile facts
"""
import argparse

import yaml

from core.config import SEMANTIC_AUTO
from core.db import connect
from core.llm import PROVIDERS, ask_llm, extract_block


def profile_database(con):
    """Facts that help guess meaning: row counts, types, value lists, ranges, examples, likely joins."""
    profile = {"tables": {}, "possible_joins": []}
    col_tables = {}
    for (t,) in con.execute("SHOW TABLES").fetchall():
        n = con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
        info = {"row_count": n, "columns": {}}
        for name, ctype, *_ in con.execute(f"DESCRIBE {t}").fetchall():
            col_tables.setdefault(name, []).append(t)
            distinct = con.execute(f'SELECT COUNT(DISTINCT "{name}") FROM {t}').fetchone()[0]
            col = {"type": ctype, "distinct": distinct}
            if distinct <= 12:
                vals = con.execute(f'SELECT "{name}", COUNT(*) c FROM {t} GROUP BY 1 ORDER BY c DESC').fetchall()
                col["values"] = {str(v): c for v, c in vals}
            elif any(k in ctype for k in ("INT", "DECIMAL", "DOUBLE", "TIMESTAMP", "DATE")):
                lo, hi = con.execute(f'SELECT MIN("{name}"), MAX("{name}") FROM {t}').fetchone()
                col["min"], col["max"] = str(lo), str(hi)
            else:
                col["examples"] = [str(r[0]) for r in con.execute(
                    f'SELECT DISTINCT "{name}" FROM {t} WHERE "{name}" IS NOT NULL LIMIT 3').fetchall()]
            info["columns"][name] = col
        profile["tables"][t] = info
    for col, ts in col_tables.items():
        for i in range(len(ts)):
            for j in range(i + 1, len(ts)):
                profile["possible_joins"].append(f"{ts[i]}.{col} = {ts[j]}.{col}")
    return profile


PROMPT = """You are a senior data engineer. Below is a profile of an e-commerce marketplace database.
Write a SEMANTIC MODEL in YAML that explains the business meaning of the data so another AI can write
correct SQL for business questions.

Include these sections:
tables:        per table a description and the meaning of important columns (list codes and their meanings)
joins:         list of join conditions
rules:         general rules (which order statuses count for sales, which date column to use, naming...)
metrics:       definitions (as SQL logic) for revenue, orders, average order value, customers, freight,
               late delivery rate, delivery days, repeat customers, review score, payment share
Be concrete and short. If unsure, give your best guess.

Database profile:
{profile}

Return only YAML inside a ```yaml code block."""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--provider", default="groq", choices=PROVIDERS + ["profile"])
    ap.add_argument("--model", default="")
    args = ap.parse_args()

    profile_yaml = yaml.safe_dump(profile_database(connect()), sort_keys=False, allow_unicode=True)
    if args.provider == "profile":
        text = "# Profile only (no AI): facts without business meaning.\n" + profile_yaml
    else:
        print("Asking the AI to write the semantic model...")
        text = extract_block(ask_llm(args.provider, args.model, PROMPT.format(profile=profile_yaml),
                                     max_tokens=6000), "yaml")
        yaml.safe_load(text)  # fail loudly if the AI returned broken YAML
        text = f"# AUTO-GENERATED by {args.provider} {args.model or '(default model)'} -- not reviewed by a human\n" + text
    SEMANTIC_AUTO.write_text(text, encoding="utf-8")
    print(f"Saved {SEMANTIC_AUTO} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
